name: compile for Windows, Linux, OSX (x64/x32)
on:
  workflow_dispatch:
  push:
    branches: ["dev"]
    paths: ["Natives/**"]

env:
  LIB_NAME: LinkitNatives


jobs:
  Windows:
    name: Windows x32 / x64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: x64
        run: |
          cd D:\a\Linkit\Linkit\Natives
          cmake --build . --target ALL_BUILD --config Release
          mkdir Build
          move cmake-build-debug/%LIB_NAME%.dll Build/%LIB_NAME%-x64.dll
      - name: x32
        run: |
          cd D:\a\Linkit\Linkit\Natives
          cmake --build . --target ALL_BUILD --config Release
          dir cmake-build-debug
          move cmake-build-debug/%LIB_NAME%.dll Build/%LIB_NAME%-x32.dll
          
          
