name: Natives
on:
  workflow_dispatch:
  push:
    branches: [ "dev" ]
    paths: [ "Natives/**" ]

env:
  LIB_NAME: LinkitNatives


jobs:
  Windows:
    name: Windows x64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile binaries
        run: |
          cd Natives
          mkdir build && cd build && cmake .. && cmake --build . --config Release
  MacOS:
    name: Macos x64
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile binaries
        run: |
          cd Natives
          mkdir build && cd build && cmake .. && cmake --build . --config Release
  Unix:
    name: Unix x64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile binaries
        run: |
          cd Natives
          mkdir build && cd build && cmake .. && cmake --build . --config Release
      - name: Generate settings.xml for Maven Builds
        uses: whelk-io/maven-settings-xml-action@v20
        with:
          repositories: '[{"id": "central", "url": "https://repo1.maven.org/maven2"},{"id": "github", "url": "https://maven.pkg.github.com/Override-6/Linkit", "releases": {"enabled": "true"}, "snapshots": {"enabled": "true"}}]'
          servers: '[{"id": "github", "username": "Override-6", "password": "$PACKAGES_DEPLOY_PAT"}]'
