

name: Natives

on:
  workflow_dispatch:
  push:
    branches: [ "dev" ]
    paths: [ "Natives/**" ]

env:
  LIB_NAME: LinkitNatives
  PACKAGES_DEPLOY_PAT: ${{secrets.PACKAGES_DEPLOY_PAT}}

jobs:
  Windows:
    name: Windows x64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile binaries
        run: |
          cd Natives
          mkdir build && cd build && cmake .. && cmake --build . --config Release
      - name: commit
        run: |
          mkdir Natives/bins
          move Natives/build/$LIB_NAME.dll Natives/bins/$LIB_NAME.dll
          
          git config --global user.email maximebatista18@gmail.com
          git config --global user.name "Override-6 [bot]"
          
          git add .
          git fetch
          git commit -m "binaries update for `windows` "
          git push
  MacOS:
    name: Macos x64
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile binaries
        run: |
          cd Natives
          mkdir build && cd build && cmake .. && cmake --build . --config Release
      - name: commit
        run: |
          mkdir -p Natives/bins
          mv Natives/build/$LIB_NAME.dylib Natives/bins/$LIB_NAME.dylib
          
          git config --global user.email maximebatista18@gmail.com
          git config --global user.name "Override-6 [bot]"
          
          git add .
          git fetch
          git commit -m "binaries update for `macos`"
          git push
  Unix:
    name: Unix x64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Compile binaries
        run: |
          cd Natives
          mkdir build && cd build && cmake .. && cmake --build . --config Release
      - name: commit
        run: |
          mkdir -p Natives/bins
          mv Natives/build/$LIB_NAME.so Natives/bins/$LIB_NAME.so
          
          git config --global user.email maximebatista18@gmail.com
          git config --global user.name "Override-6 [bot]"
          
          git add .
          git fetch
          git commit -m "binaries update for `unix`"
          git push