name: compile for Windows, Linux, OSX (x64/x32)
on:
  workflow_dispatch:
  push:
    branches: ["dev"]
    paths: ["Natives/**"]

env:
  LIB_NAME: LinkitNatives


jobs:
  Windows:
    name: Windows x64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: x64
        run: |
          cd D:\a\Linkit\Linkit\Natives
          mkdir build
          cd build && cmake .. && cmake --build . --config Release 
          dir
          
          
