name: Natives
on:
  workflow_dispatch:
  push:
    branches: ["dev"]
    paths: ["Natives/**"]

env:
  LIB_NAME: LinkitNatives


jobs:
  Windows:
    name: Windows x64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: x64
        run: |
          cd Natives
          mkdir build
          cd build && cmake .. && cmake --build . --config Release 
  MacOS:
    name: Macos x64
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: x64
        run: |
          pwd
          cd Natives
          ls /Users/runner/hostedtoolcache/Java_Temurin-Hotspot_jdk/8.0.345-1/x64/Contents/Home/include/
          mkdir build
          cd build && cmake .. && cmake --build . --config Release 

  Unix:
    name: Unix x64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: x64
        run: |
          pwd
          cd Natives
          mkdir build
          cd build && cmake .. && cmake --build . --config Release 
         
