name: compile for Windows, Linux, OSX (x64/x32)
on:
  workflow_dispatch:
  push:
    branches:
      - dev
jobs:
  Windows:
    name: Windows x32 / x64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: x64
        run: |
          cd D:\a\Linkit\Linkit\Natives
          cmake . -DCMAKE_GENERATOR_PLATFORM=x64 --config Release
          mkdir Build
          dir cmake-build-debug
          move cmake-build-debug/LinkitNativesLibraries.dll Build/LinkitNativesLibraries-x64.dll
      - name: x32
        run: |
          cd D:\a\Linkit\Linkit\Natives
          cmake . -DCMAKE_GENERATOR_PLATFORM=x32 --config Release
          dir
          move cmake-build-debug/LinkitNativesLibraries.dll Build/LinkitNativesLibraries-x32.dll
          
          
