name: compile for Windows, Linux, OSX (x64/x32)
on:
  push:
    branches:
      - dev
jobs:
  Windows:
    name: Windows x32 / x64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          gcc --version
