name: compile for Windows, Linux, OSX (x64/x32)
on:
  workflow_dispatch:
  push:
    branches:
      - dev
jobs:
  Windows:
    name: Windows x32 / x64
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd D:\a\Linkit\Linkit\Natives
          cmake -DCMAKE_BUILD_TYPE=Release . -DCMAKE_GENERATOR_PLATFORM=x64
          mkdir Build
          dir
          move cmake-build-release/LinkitNativesLibraries.dll Build/LinkitNativesLibraries-x64.dll
          
          
