name: deploy scaladoc on wiki

on:
  push:
    branches: [ "dev" ]
    paths: [ "**.java", "**.scala" ]

  pull_request:
    branches: [ "dev" ]
    paths: [ "**.java", "**.scala" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3.4.1
        with:
          distribution: 'adopt' # See 'Supported distributions' for available options
          java-version: '19'
      - name: prepare Temp dirs result
        run: |
           cd /home/runner/work
           mkdir Temp
      - name: generate scaladocs
        run: |
           chmod +x ./gradlew
           ./gradlew generateScaladocs

      - name: move generated docs in Temp dirs
        run: |
           mkdir -p /home/runner/work/Temp/ 
           cp -R /home/runner/work/Linkit/Linkit/build/docs/scaladoc/* /home/runner/work/Temp/ 
      - name: checkout to gh-pages and commit
        run: |
           cd /home/runner/work/Linkit/Linkit/
           git fetch
           git checkout -f gh-pages
           cp -R /home/runner/work/Temp/* /home/runner/work/Linkit/Linkit/scaladoc
           git config user.name "Override-6 [Bot]"
           git config user.email maximebatista18@gmail.com
           git add scaladoc/\*
           git commit --allow-empty -m "auto generated scaladoc"
           git push
          
 
