# This is a basic workflow to help you get started with Actions

name: deploy scaladoc on wiki

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "redesign/syncobjects_contract" branch
  push:
    branches: [ "redesign/syncobjects_contract" ]
  pull_request:
    branches: [ "redesign/syncobjects_contract" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: setup java jdk
        uses: actions/setup-java@v3.4.1
        with:
           distribution: 'adopt' # See 'Supported distributions' for available options
           java-version: '17'
      - name: prepare Temp dirs result
        run: |
           cd /home/runner/work
           mkdir Temp
      - name: generate scaladocs
        run: |
           chmod +x ./gradlew
           ./gradlew Engine:scaladoc
           ./gradlew API:scaladoc
           ./gradlew Server:scaladoc
           ./gradlew Client:scaladoc

      - name: move generated docs in Temp dirs
        run: |
           cp -R /home/runner/work/Linkit/Engine/build/docs/scaladoc/* /home/runner/work/Temp/Engine/
           cp -R /home/runner/work/Linkit/API/build/docs/scaladoc/* /home/runner/work/Temp/API/
           cp -R /home/runner/work/Linkit/Server/build/docs/scaladoc/* /home/runner/work/Temp/Server/
           cp -R /home/runner/work/Linkit/Client/build/docs/scaladoc/* /home/runner/work/Temp/Client/
        
      - name: checkout to gh-pages and commit
        run: |
           git checkout gh-pages
           cp -R /home/runner/work/Temp/Engine/* /home/runner/work/Linkit/static/scaladoc 
           cp -R /home/runner/work/Temp/API/* /home/runner/work/Linkit/static/scaladoc  
           cp -R /home/runner/work/Temp/Server/* /home/runner/work/Linkit/static/scaladoc 
           cp -R  /home/runner/work/Temp/Client/* /home/runner/work/Linkit/Client/build/docs/scaladoc/*
          
 
